/**:
  ros__parameters:
    product_name: LDLiDAR_LD19
    topic_name: scan
    frame_id: laser_frame
    port_name: /tmp/lidar
    port_baudrate: 230400
    laser_scan_dir: true
    enable_angle_crop_func: false
    angle_crop_min: 135.0
    angle_crop_max: 225.0
